module.exports = [
  {
    id: "visit-brussels",
    name: "Visit Brussels",
    city: "Brussels",
    website: "https://www.visit.brussels/",
    agendaUrl:
      "https://www.visit.brussels/content/visitbrussels/en/visitors/agenda/all-events-wizard/jcr:content/root/container/agendafinder.feed.json",
    kind: "city",
    active: true,
  },
  {
    id: "brussels-city",
    name: "City of Brussels",
    city: "Brussels",
    website: "https://www.brussels.be/",
    agendaUrl: "https://www.brussels.be/agenda",
    kind: "city",
    active: true,
  },
  {
    id: "ab-concerts",
    name: "Ancienne Belgique",
    city: "Brussels",
    website: "https://www.abconcerts.be/en",
    agendaUrl: "https://www.abconcerts.be/en/agenda",
    kind: "venue",
    active: true,
  },
  {
    id: "visit-ghent",
    name: "Visit Gent",
    city: "Ghent",
    website: "https://visit.gent.be/en",
    agendaUrl: "https://visit.gent.be/en/calendar/events?f%5B0%5D=event_category%3A17",
    kind: "city",
    active: true,
  },
  {
    id: "visit-leuven",
    name: "Visit Leuven",
    city: "Leuven",
    website: "https://www.visitleuven.be/en",
    agendaUrl: "https://www.visitleuven.be/en/events",
    kind: "city",
    active: true,
  },
  {
    id: "uit-in-leuven",
    name: "UiT in Leuven",
    city: "Leuven",
    website: "https://www.uitinleuven.be/",
    agendaUrl: "https://www.uitinleuven.be/agenda",
    kind: "venue-network",
    active: true,
  },
  {
    id: "visit-liege",
    name: "Visitez Liège",
    city: "Liege",
    website: "https://www.visitezliege.be/",
    agendaUrl:
      "https://www.visitezliege.be/fr/catalogue/evenement/musique?commune=liege&compatibleindividuel=True",
    kind: "city",
    active: true,
  },
  {
    id: "visit-bruges",
    name: "Visit Bruges",
    city: "Bruges",
    website: "https://www.visitbruges.be/en",
    agendaUrl:
      "https://www.visitbruges.be/en/whats-on/events-calendar?field_tags%5B309%5D=309",
    kind: "city",
    active: true,
  },
  {
    id: "visit-mons",
    name: "Visit Mons",
    city: "Mons",
    website: "https://www.visitmons.be/",
    agendaUrl: "https://www.visitmons.be/fr/agenda/concerts",
    kind: "city",
    active: true,
  },
  {
    id: "charleroi",
    name: "Ville de Charleroi",
    city: "Charleroi",
    website: "https://www.charleroi.be/",
    agendaUrl: "https://www.charleroi.be/agenda",
    kind: "city",
    active: true,
  },
  {
    id: "visit-namur",
    name: "Visit Namur",
    city: "Namur",
    website: "https://destination.visitnamur.eu/",
    agendaUrl: "https://destination.visitnamur.eu/agenda/",
    kind: "city",
    active: true,
  },
  {
    id: "visit-hasselt",
    name: "Visit Hasselt",
    city: "Hasselt",
    website: "https://www.visitlimburg.be/nl/wat-te-doen/visit-hasselt",
    agendaUrl: "https://www.visitlimburg.be/nl/hasselt/hasselt",
    kind: "city",
    active: true,
  },
  {
    id: "trix",
    name: "Trix",
    city: "Antwerp",
    website: "https://www.trixonline.be/en",
    agendaUrl: "https://www.trixonline.be/en/program/?type=concert",
    kind: "venue",
    active: true,
  },
  {
    id: "de-roma",
    name: "De Roma",
    city: "Antwerp",
    website: "https://www.deroma.be/en/",
    agendaUrl: "https://www.deroma.be/en/agenda",
    kind: "venue",
    active: true,
  },
  {
    id: "ccha",
    name: "CCHA",
    city: "Hasselt",
    website: "https://www.ccha.be/",
    agendaUrl: "https://www.ccha.be/concerten",
    kind: "venue",
    active: true,
  },
  {
    id: "uit-in-mechelen",
    name: "UiT in Mechelen",
    city: "Mechelen",
    website: "https://uitin.mechelen.be/",
    agendaUrl: "https://uitin.mechelen.be/agenda?facets%5B1%5D%5Bwhat%5D%5B0.50.4.0.0%5D=Concert",
    kind: "venue-network",
    active: true,
  },
  {
    id: "uit-in-vlaanderen",
    name: "UiT in Vlaanderen",
    city: "Belgium",
    website: "https://www.uitinvlaanderen.be/",
    agendaUrl: "https://www.uitinvlaanderen.be/agenda/muziek",
    kind: "network",
    active: true,
  },
  {
    id: "eventbrite-belgium",
    name: "Eventbrite Belgium Music",
    city: "Belgium",
    website: "https://www.eventbrite.com/",
    agendaUrl: "https://www.eventbrite.com/b/belgium/music/",
    kind: "network",
    active: true,
  },
  {
    id: "bozar",
    name: "Bozar",
    city: "Brussels",
    website: "https://www.bozar.be/en/",
    agendaUrl: "https://www.bozar.be/en/calendar",
    kind: "venue",
    active: false,
  },
  {
    id: "botanique",
    name: "Botanique",
    city: "Brussels",
    website: "https://botanique.be/en",
    agendaUrl: "https://botanique.be/en",
    kind: "venue",
    active: false,
  },
  {
    id: "het-depot",
    name: "Het Depot",
    city: "Leuven",
    website: "https://www.hetdepot.be/",
    agendaUrl: "https://www.hetdepot.be/en/agenda",
    kind: "venue",
    active: false,
  },
  {
    id: "de-bijloke",
    name: "de Bijloke",
    city: "Ghent",
    website: "https://www.debijloke.be/",
    agendaUrl: "https://www.debijloke.be/agenda",
    kind: "venue",
    active: false,
  },
  {
    id: "flagey",
    name: "Flagey",
    city: "Brussels",
    website: "https://www.flagey.be/en/",
    agendaUrl: "https://www.flagey.be/en/program/1-music",
    kind: "venue",
    active: false,
  },
];
